= tcp/ip stack


不能插入图片，我也是醉了Stack Exchange Inbox Reputation and Badges sign up log in tour help  

Search Q&A

Stack Overflow
Questions
 
Jobs
 
Tags
 
Users
 
Badges
 
Ask Question
_ Stack Overflow is a community of 4.7 million programmers, just like you, helping each other. 

Join them; it only takes a minute:

Sign up
Join the Stack Overflow community to:
Ask programming questions Answer and help your peers Get recognized for your expertise
Unable to establish SSL connection upon wget on Ubuntu 14.04 LTS


up vote
3
down vote
favorite
1
I tried to download an image through wget but I got an error: Unable to establish SSL connection.

wget https://www.website.com/image.jpg
--2015-02-26 01:30:17--  https://www.website.com/image.jpg
Resolving www.website.com (www.website.com)... xx.xxx.xx.xx
Connecting to www.website.com (www.website.com)|xx.xxx.xx.xx|:443... connected.
Unable to establish SSL connection.
My test case:

Using Ubuntu 12.04.4 LTS (GNU/Linux 3.8.0-44-generic x86_64), GNU Wget 1.13.4 built on linux-gnu, I was able to download the image using the code above. No error.
Using Ubuntu 14.04 LTS (GNU/Linux 3.13.0-24-generic x86_64), GNU Wget 1.15 built on linux-gnu, I was not able to download the image using the code above.
Another variable is that the www.website.com uses TLS 1.0. I don't have an idea how this affects wget. But if I wget an image from TLS 1.2 websites I don't get any ssl connection errors from both test cases.

Is Ubuntu 14.04 or wget 1.15 not compatible with TLS 1.0 websites? Do I need to install/download any library/software to enable this connection?

linux ubuntu ssl wget
shareimprove this question
asked Feb 27 '15 at 3:52

xanderlopez
6527
  	 	
This sounds like the wget is failing during the SSL handshake. This is most likely occurring because your Ubuntu 14.04 does not trust the domain www.website.com. You may need to install this website's server certificate into your trust store. – Tim Biegeleisen Feb 27 '15 at 4:10
  	 	
If this error happens with any other SSL site too add this information to your question. If this happens only with a specific site and if this site works in the browser show the exact URL. If this site does not work in the browser too it is a problem if the site itself. – Steffen Ullrich Feb 27 '15 at 5:13 
  	 	
@TimBiegeleisen I downloaded www.website.com's certificate through Chrome: clicked lock sign -> connection tab -> certificate information link -> details -> URI link. Then I copied it to the server, then followed how to install root certificate (askubuntu.com/questions/73287/…). Then after /etc/ssl/certs$ ls, I found the certificate there. I tried to wget again but I still get the same error. – xanderlopez Feb 27 '15 at 7:12 
  	 	
@SteffenUllrich right now it happens only to the website I'm testing. I can't post it here because it's confidential. – xanderlopez Feb 27 '15 at 7:17
  	 	
Possible duplicate of Unable to establish SSL connection, how do I fix my SSL cert? – kenorb Feb 2 at 11:30
add a comment
2 Answers
active oldest votes
up vote
5
down vote
accepted
... right now it happens only to the website I'm testing. I can't post it here because it's confidential.
Then I guess it is one of the sites which is incompatible with TLS1.2. The openssl as used in 12.04 does not use TLS1.2 on the client side while with 14.04 it uses TLS1.2 which might explain the difference. To work around try to explicitly use 
--secure-protocol=TLSv1. If this does not help check if you can access the site with openssl s_client -connect ... (probably not) and with openssl s_client -tls1 -no_tls1_1, -no_tls1_2 ....

Please note that it might be other causes, but this one is the most probable and without getting access to the site everything is just speculation anyway.

The assumed problem in detail: Usually clients use the most compatible handshake to access a server. This is the SSLv23 handshake which is compatible to older SSL versions but announces the best TLS version the client supports, so that the server can pick the best version. In this case wget would announce TLS1.2. But there are some broken servers which never assumed that one day there would be something like TLS1.2 and which refuse the handshake if the client announces support for this hot new version (from 2008!) instead of just responding with the best version the server supports. To access these broken servers the client has to lie and claim that it only supports TLS1.0 as the best version.

Is Ubuntu 14.04 or wget 1.15 not compatible with TLS 1.0 websites? Do I need to install/download any library/software to enable this connection?
The problem is the server, not the client. Most browsers work around these broken servers by retrying with a lower version. Most other applications fail permanently if the first connection attempt fails, i.e. they don't downgrade by itself and one has to enforce another version by some application specific settings.

shareimprove this answer
edited Feb 27 '15 at 7:46
answered Feb 27 '15 at 7:40

Steffen Ullrich
27.1k21347
add a comment

up vote
0
down vote
If you trust the host, either add the valid certificate, specify --no-check-certificate or add:

check_certificate = off
into your ~/.wgetrc.

In some rare cases, your system time could be out-of-sync therefore invalidating the certificates.

shareimprove this answer
answered Feb 2 at 11:33

kenorb
13.5k79486
add a comment
Your Answer


 
Sign up or log in

Sign up using Google
Sign up using Facebook
Sign up using Email and Password
Post as a guest

Name

Email

required, but never shown
 Post Your Answer
By posting your answer, you agree to the privacy policy and terms of service.

Not the answer you're looking for?	Browse other questions tagged linux ubuntu ssl wget or ask your own question.

asked

1 year ago

viewed

9884 times

active

2 months ago


Looking for a job?
ソリューション・エンジニア - Solution Engineer
アクセンチュアテクノロジー Accenture TechnologyTokyo, Japan
pythonjava
Web Developer
Univa PaycastMinato, Japan
javajavascript
Software Engineer (Scala/Ruby/Java)
M3, Inc.Tokyo, Japan
javaruby-on-rails
Data Science Engineer
RakutenSetagaya, Japan
javahadoop
Linked

29 Unable to establish SSL connection, how do I fix my SSL cert?
Related

2 why can't get this page using wget(ubuntu)?
29 Unable to establish SSL connection, how do I fix my SSL cert?
0 Unable to establish SSL connection while setting up SSL on Ubuntu/Apache2
0 MySQL 5.5 and SSL on Ubuntu 14.04
0 Unable to connect (trying to set up SSL in ubuntu)
0 How do I upgrade docker on my Ubuntu 14.04 machine?
1 arcanist / curl is unable to make ssl connections
0 Cant connect to mysql ssl with compiled php (ubuntu 12)
0 Ubuntu 14.04 - wget is hanging
0 Ubuntu install Java8 got Error “Unable to establish SSL connection. ” How can I fix it?
Hot Network Questions

English word for "repetitive, boring work"?
Why does everyone use git in a centralized manner?
Can Goodberry be used to summon watermelons?
What are the programming and computer references in Steins;Gate?
Can a shield be used with Mage Armor?
What is the correct spelling of the head of the Derbytantes group?
How to add more polygons in edit mode
Can a plant evolve to give off CO2?
How I can align 2 arrays?
Riddles whose answer is "the moon"
Why are there so many primes in the convergents of Pi?
What is "Soft Coding", really?
Has Batman ever fought Hawkman?
Copycat Chess (Part 3/3)
Does sum of the reciprocals of all the composite numbers converge?
A (440 Hz) and A (880 Hz) are completely different sounds to me. Does this mean I'm tone deaf?
Are backpacks accepted in most American work places? If so, for how long?
Are there German words that get pronounced differently based on whether they are capitalized?
Methods (mechanics) to select a set of pictures from large amounts
Greatest Common Divisor
This C function should only return false, but it doesn’t
The Russian equivalent of 'meeting', as in team meeting
Probability of Winning in Sports
What does "int& foo()" mean in C++?
question feed
about us tour help blog chat data legal privacy policy work here advertising info mobile contact us feedback
TECHNOLOGY	LIFE / ARTS	CULTURE / RECREATION	SCIENCE	OTHER
Stack Overflow
Server Fault
Super User
Web Applications
Ask Ubuntu
Webmasters
Game Development
TeX - LaTeX
Programmers
Unix & Linux
Ask Different (Apple)
WordPress Development
Geographic Information Systems
Electrical Engineering
Android Enthusiasts
Information Security
Database Administrators
Drupal Answers
SharePoint
User Experience
Mathematica
Salesforce
ExpressionEngine® Answers
more (13)
Photography
Science Fiction & Fantasy
Graphic Design
Movies & TV
Seasoned Advice (cooking)
Home Improvement
Personal Finance & Money
Academia
more (9)
English Language & Usage
Skeptics
Mi Yodeya (Judaism)
Travel
Christianity
Arqade (gaming)
Bicycles
Role-playing Games
more (21)
Mathematics
Cross Validated (stats)
Theoretical Computer Science
Physics
MathOverflow
Chemistry
Biology
more (5)
Stack Apps
Meta Stack Exchange
Area 51
Stack Overflow Careers
site design / logo © 2016 Stack Exchange Inc; user contributions licensed under cc by-sa 3.0 with attribution required
rev 2016.4.8.3448